### ISSUE TITLE
rapl_finalize should not automatically restore registers

### ISSUE THREAD

**Issue by connorimes** [LLNL/libmsr#17]
The documentation for `rapl_finalize` (currently unimplemented) seems to indicate that in the future it will "will restore rapl registers to their state prior to execution" as well as cleanup memory.  The latter is, of course, necessary.  However, should this function be implemented, restoring registers to their initial values should be a separate function, or in the very least a boolean parameter to the finalize function.  The user should be able to decide the final state of the MSRs when tearing down.  There are use cases where libmsr can be used to configure MSRs with the intent of the changes outlasting the program's (or program component's) lifetime.

**Comment by slabasan** [comment]
Thanks for the note. 

For the most up-to-date documentation, I suggest viewing the Doxygen code here (software.llnl.gov/libmsr) or building the documentation yourself with 'make doc'. At this point, I'm not sure if restoring the MSRs is in the plans for libmsr. Can you elaborate on what some of these use cases may be? We have a utility included with libmsr called msrmod, which provides users with a quick way to modify MSRs. This may be more suited to your needs than writing a whole libmsr program.

**Comment by connorimes** [comment]
Sure.  The simplest example would be any case where libmsr is cleaned up/finished/destroyed before the application is finished running.  It seems like libmsr's normal use case is that the application is directly managing it, but this needn't always be the case.  Libmsr can very easily be a transitive dependency on another library, in which case the application is not managing libmsr's lifecycle directly (and perhaps may be unaware of libmsr's behavior).

Another example is an application whose purpose is to actually manipulate power settings.  Changes in settings need to persist after the program completes, but the program shouldn't be prevented from cleaning up resources properly before termination just to avoid resetting the register values.  The msrmod program appears to require at least some knowledge about MSRs, whereas abstractions may be preferable for many people.

For instance, I have a common interface (code not yet released) for getting/setting RAPL power caps with a variety of library implementations, one of which depends on libmsr (making libmsr a transitive dependency of any code that depends on my library).  My library may be initialized and torn down at any point during an application's runtime, perhaps even multiple times.  Of course I don't want memory leaks caused by not calling rapl_finish.  I also expose a binary to manipulate power settings which doesn't require the users to know anything about how to actually use MSRs.

In the design of my own library, I also run into the concern where multiple components may depend on libmsr independently, with each trying to manage libmsr's lifecycle.  Because libmsr stores its state in private variables rather than a user-allocated struct, this use case is problematic.  This would require a much bigger change to libmsr, which is why I haven't requested it thus far.  It is beyond the original intent of the report, but I thought was worth mentioning now having introduced the use case of libmsr as a transitive dependency.

Cheers.

**Comment by slabasan** [comment]
@connorimes Sorry for the delay. We agree with your comments and do not see a need to include automatic register restore functionality in source. I will make a note to update the documentation to reflect this. Should a user need to restore the registers, there is a utility called msrsave, which can be found here: https://github.com/llnl/msr-safe.

In regards to the private variables, we are looking into possible modifications to libmsr's infrastructure, one of them being a change in how libmsr manages MSR data. Thank you for detailing all of the use cases!

**Comment by connorimes** [comment]
Thanks @slabasan .  Are there still plans to introduce a `rapl_finalize` function to cleanup memory?

**Comment by slabasan** [comment]
Libmsr currently has a `finalize_msr()` function that should do all the memory cleanup you need.
