### ISSUE TITLE
pstate-test Command-line Arg Handling

### ISSUE THREAD

**Issue by pdesupinski** [LLNL/libmsr#18]
In pstate_test.c, the main function contains this code:
```c    
    else if (argc > sockets)
    {
        fprintf(stderr, "ERROR: Too many p-states (in GHz) specified.\n");
        return -1;
    }
    else if (argc == sockets+1)
    {
        new_p_states_ghz[0] = atof(argv[1]);
        new_p_states_ghz[1] = atof(argv[2]);
    }
```

The second else if block is not reachable because sockets+1 > sockets, so command-lines such as ./pstate-test 1.8 1.9 cause an error with 2 sockets.

**Comment by slabasan** [comment]
Thanks for the feedback. I fixed the incorrect argument parsing here: `09686c`.
