### ISSUE TITLE
make distclean recursively removes CMAKE_INSTALL_PREFIX

### ISSUE THREAD

**Issue by connorimes** [LLNL/libmsr#20]
This needs to be critical priority.  The `distclean` target recursively deletes the cmake install prefix, which on many Linux systems is `/usr/local/`!  This command can wreck an entire system.  I really hope I didn't have anything writable there when I executed this (fortunately without sudo).

`rm -rf ${CMAKE_INSTALL_PREFIX}`

**Comment by slabasan** [comment]
Hi @connorimes, I just removed the `CMAKE_INSTALL_PREFIX` from the `distclean` target. Thank you for your feedback. We greatly appreciate it!

**Comment by connorimes** [comment]
Thanks.  I recommend adding a custom `uninstall` target.  That's what I do with my projects.

https://cmake.org/Wiki/CMake_FAQ#Can_I_do_.22make_uninstall.22_with_CMake.3F
