### ISSUE TITLE
Create a testing suite/travis CI

### ISSUE THREAD

**Issue by tpatki** [LLNL/libmsr#29]
Just opening an issue here to keep a note about our discussions from this past week.

In general, we need more rigorous testing of individual features, and a way to test platform dependence (if any). We have some examples/tests, but these are not diverse enough to provide good coverage, and are not integrated into regular daily/weekly/PR-based builds.

**Comment by tapaswenipathak** [comment]
Hi @tpatki -

Reading the tickets this seems like a stable and inactive project, do you still need Travis setup on this repository?

**Comment by tpatki** [comment]
@tapaswenipathak: Hi Tejasweni, this is a stable and ~active~ project. We're not doing a Travis setup due to dependencies on low-level microarchitectures. Please feel free to ask questions and we will be happy to help you get it up and running.

**Comment by tpatki** [comment]
If you'd like to help address some of the issues (looking at your comments), we (@slabasan, you and I) can have a quick call to see where you can contribute best.

**Comment by tapaswenipathak** [comment]
Sure, works w/ me. Just dropped a mail.


- Tapasweni

**Comment by tapaswenipathak** [comment]
Sure, works w/ me. Just dropped a mail.

On Sat, Apr 20, 2019 at 8:21 PM Tapasya Patki <notifications@github.com> wrote:
>
> If you'd like to help address some of the issues (looking at your comments), we (@slabasan, you and I) can have a quick call to see where you can contribute best.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Tapasweni
