### ISSUE TITLE
More descriptive errors when building on unsupported platforms

### ISSUE THREAD

**Issue by rountree** [LLNL/libmsr#31]
rountree@feyerabend:~/local/libmsr$ make
ERROR: unable to open file platform_headers/Intel9E.h
Model 9e may not be supported. Use -f to force.
-- HWLOC library found using find_library()
--   HWLOC_INCLUDE_DIRS = /usr/include
--   HWLOC_LIBRARY = /usr/lib/x86_64-linux-gnu/libhwloc.so
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/rountree/local/libmsr
Scanning dependencies of target msr
[  1%] Building C object src/CMakeFiles/msr.dir/cpuid.c.o
[  3%] Building C object src/CMakeFiles/msr.dir/csr_core.c.o
[  5%] Building C object src/CMakeFiles/msr.dir/csr_imc.c.o
In file included from /home/rountree/local/libmsr/src/csr_imc.c:46:0:
/home/rountree/local/libmsr/include/csr_imc.h:39:10: fatal error: master.h: No such file or directory
 #include "master.h"
          ^~~~~~~~~~
compilation terminated.
src/CMakeFiles/msr.dir/build.make:110: recipe for target 'src/CMakeFiles/msr.dir/csr_imc.c.o' failed
make[2]: *** [src/CMakeFiles/msr.dir/csr_imc.c.o] Error 1
CMakeFiles/Makefile2:119: recipe for target 'src/CMakeFiles/msr.dir/all' failed
make[1]: *** [src/CMakeFiles/msr.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by slabasan** [comment]
@rountree Which architecture were you trying to build this on? DO I have access to it?

**Comment by rountree** [comment]
It was my home machine:  Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
Model is 0x9E.

**Comment by slabasan** [comment]
Libmsr does not yet support Kaby Lake. Want to add a new platform header `Intel9E.h` for this platform?

**Comment by scott-walker-llnl** [comment]
If you need a fast solution, just tell the libmsr build script to force the
Haswell header files (used to be -f3F). There is not a big difference
between kabylake and haswell in terms of registers. I have my own msr-safe
whitelist for kabylake (same processor) and here is the diff from wl_063F.

56c56,57
< 0x0000064F    0x0000000000000000      # "MSR_CORE_PERF_LIMIT_REASONS"
---
> 0x0000064F    0x000000003DF30000      # "MSR_CORE_PERF_LIMIT_REASONS"
> 0x00000770    0x0000000000000000      # "HWP_ENABLE"

**Comment by slabasan** [comment]
Going to update the title to better capture the issue. The issue here is that libmsr does not support Kaby Lake, so there is no platform_headers for this architecture. It is not clear from the build errors that the architecture 9E is not supported.
