### ISSUE TITLE
Macro redefinition warning of "UINT_MAX"

### ISSUE THREAD

**Issue by danielecesarini** [LLNL/libmsr#34]
In "msr_rapl.h" there is the macro definition:

`#define UINT_MAX 4294967295U`

The macro definition is taken from "limits.h" (as the comment say) but if I need to use "limits.h" (or a library which include "limits.h", as instance HWLOC library) this macro consequently raises a warning because the compiler discover a macro redefinition.

**Comment by danielecesarini** [comment]
`In file included from /homeworkspace/myproject/include_file.h(57), from /home/workspace/myproject/file.c(34):
/home/workspace/libmsr/include/msr_rapl.h(110): warning #47: incompatible redefinition of macro "UINT_MAX" (declared at line 97 of "/opt/intel/pe-xe-2017/binary/compilers_and_libraries_2017.4.196/linux/compiler/include/limits.h")
  #define UINT_MAX 4294967295U // taken from limits.h`

**Comment by slabasan** [comment]
Thanks @danielecesarini! I haven't had a chance to test this, but if we were to remove the UINT_MAX macro and instead include limits.h, would this resolve the issue?

**Comment by danielecesarini** [comment]
Yes, it works.
