### ISSUE TITLE
/dev/cpu/*/msr_safe permissions

### ISSUE THREAD

**Issue by vysocky** [LLNL/libmsr#37]
Hi all,
I've installed libmsr on a new system and I've found out, that `/dev/cpu/*/msr_safe` requires read and write permissions, however `/dev/cpu/*/msr` doesn't. 

README says that it is the opposite way: https://github.com/LLNL/libmsr/blob/master/README#L72

Ondra

**Comment by slabasan** [comment]
Thanks @vysocky for the feedback. I've updated the README.
