### ISSUE TITLE
intel cpu frequency

### ISSUE THREAD

**Issue by nikitavedre** [LLNL/libmsr#39]
can we this repository to set intel cpu frequency on windows?

**Comment by rountree** [comment]
Hi @nikitavedre 
As you tell from the last change dates, we've not been keeping up with this project.  Work has moved over to [Variorum](https://github.com/LLNL/variorum).

All of our development work targets the Linux environment.  However, most of the telemetry and control knobs we target are using libraries that may be available on Windows (the exception is model-specific registers on AMD and Intel, and sysfs devices on Arm).  If you wanted to port the [msr-safe](https://github.com/rountree/msr-safe) driver to Windows, then Variorum will give you a solid, useful interface.  I assume libraries like [hwloc](https://github.com/open-mpi/hwloc) have Windows ports, but I can't swear to it.

Let me know if you'd like to pursue this.  It's probably faster to contact me directly as Rountree at LLNL dot gov.
